"""add manipulation baseline fields

Revision ID: 01e1bbf6604e
Revises: 8e2ee6d17010
Create Date: 2026-05-22 21:10:34.280270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e1bbf6604e'
down_revision = '8e2ee6d17010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manipulation_check_baseline', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('manipulation_baseline_set_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_column('manipulation_baseline_set_at')
        batch_op.drop_column('manipulation_check_baseline')

    # ### end Alembic commands ###
