"""Initial baseline migration

Revision ID: 048c3585fd45
Revises: 
Create Date: 2026-05-05 11:58:18.669740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048c3585fd45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('account_size', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('profit_target', sa.Float(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=False),
    sa.Column('max_overall_loss', sa.Float(), nullable=False),
    sa.Column('min_trading_days', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('leverage', sa.String(length=20), nullable=True),
    sa.Column('user_profit_share', sa.Integer(), nullable=False),
    sa.Column('payout_cycle', sa.String(length=20), nullable=True),
    sa.Column('weekend_trading', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_template_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_template_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_template_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('id_front_url', sa.String(length=500), nullable=True),
    sa.Column('id_back_url', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_notes', sa.Text(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('phone_verification_code', sa.String(length=6), nullable=True),
    sa.Column('phone_verification_sent_at', sa.Float(), nullable=True),
    sa.Column('phone_verification_attempts', sa.Integer(), nullable=True),
    sa.Column('last_balance_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_check_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email_verification_token'), ['email_verification_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email_verified'), ['email_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_kyc_status'), ['kyc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_verified'), ['phone_verified'], unique=False)

    op.create_table('admin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_log_target_type'), ['target_type'], unique=False)

    op.create_table('challenge_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_template_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('mt5_server', sa.String(length=200), nullable=True),
    sa.Column('mt5_login', sa.String(length=100), nullable=True),
    sa.Column('mt5_password', sa.String(length=200), nullable=True),
    sa.Column('credentials_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credentials_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('serial_no', sa.Integer(), nullable=True),
    sa.Column('challenge_code', sa.String(length=6), nullable=True),
    sa.Column('challenge_token', sa.String(length=100), nullable=True),
    sa.Column('ea_connected', sa.Boolean(), nullable=True),
    sa.Column('ea_first_connection', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_profit', sa.Float(), nullable=True),
    sa.Column('current_loss', sa.Float(), nullable=True),
    sa.Column('max_drawdown_used', sa.Float(), nullable=True),
    sa.Column('starting_balance', sa.Float(), nullable=True),
    sa.Column('starting_equity', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('current_equity', sa.Float(), nullable=True),
    sa.Column('peak_equity', sa.Float(), nullable=True),
    sa.Column('daily_start_equity', sa.Float(), nullable=True),
    sa.Column('daily_start_date', sa.Date(), nullable=True),
    sa.Column('last_verified_balance', sa.Float(), nullable=True),
    sa.Column('last_verified_equity', sa.Float(), nullable=True),
    sa.Column('last_balance_check_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_check_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('violation_reason', sa.Text(), nullable=True),
    sa.Column('violation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pass_reason', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('trading_days_completed', sa.Integer(), nullable=True),
    sa.Column('mt5_account', sa.String(length=100), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_template_id'], ['challenge_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_purchase_challenge_code'), ['challenge_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_challenge_template_id'), ['challenge_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_challenge_token'), ['challenge_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_daily_start_date'), ['daily_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_ea_connected'), ['ea_connected'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_last_heartbeat'), ['last_heartbeat'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_last_updated'), ['last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_mt5_login'), ['mt5_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_serial_no'), ['serial_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_trading_days_completed'), ['trading_days_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_violation_timestamp'), ['violation_timestamp'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_ticket_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_user_id'), ['user_id'], unique=False)

    op.create_table('account_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ea_version', sa.String(length=20), nullable=True),
    sa.Column('terminal_build', sa.Integer(), nullable=True),
    sa.Column('mt5_login', sa.String(length=100), nullable=True),
    sa.Column('broker_server', sa.String(length=200), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('free_margin', sa.Float(), nullable=True),
    sa.Column('margin_used', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('profit_from_start', sa.Float(), nullable=True),
    sa.Column('drawdown_from_peak', sa.Float(), nullable=True),
    sa.Column('open_positions_count', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_snapshot', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_challenge_archived', ['challenge_purchase_id', 'is_archived'], unique=False)
        batch_op.create_index('idx_snapshot_challenge_timestamp', ['challenge_purchase_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshot_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshot_drawdown_from_peak'), ['drawdown_from_peak'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshot_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshot_mt5_login'), ['mt5_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshot_profit_from_start'), ['profit_from_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshot_timestamp'), ['timestamp'], unique=False)

    op.create_table('daily_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('start_equity', sa.Float(), nullable=False),
    sa.Column('end_equity', sa.Float(), nullable=False),
    sa.Column('start_balance', sa.Float(), nullable=False),
    sa.Column('end_balance', sa.Float(), nullable=False),
    sa.Column('lowest_equity', sa.Float(), nullable=True),
    sa.Column('highest_equity', sa.Float(), nullable=True),
    sa.Column('trades_opened', sa.Integer(), nullable=True),
    sa.Column('trades_closed', sa.Integer(), nullable=True),
    sa.Column('closed_profit', sa.Float(), nullable=True),
    sa.Column('closed_loss', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('is_trading_day', sa.Boolean(), nullable=True),
    sa.Column('violated_daily_dd', sa.Boolean(), nullable=True),
    sa.Column('had_manual_trades', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_purchase_id', 'snapshot_date', name='unique_challenge_date')
    )
    with op.batch_alter_table('daily_snapshot', schema=None) as batch_op:
        batch_op.create_index('idx_daily_challenge_date', ['challenge_purchase_id', 'snapshot_date', 'is_trading_day'], unique=False)
        batch_op.create_index('idx_daily_trading_status', ['challenge_purchase_id', 'is_trading_day', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_snapshot_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_snapshot_had_manual_trades'), ['had_manual_trades'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_snapshot_is_trading_day'), ['is_trading_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_snapshot_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_snapshot_violated_daily_dd'), ['violated_daily_dd'], unique=False)

    op.create_table('ea_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.Integer(), nullable=False),
    sa.Column('lots', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('floating_pnl', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_purchase_id', 'ticket', name='unique_challenge_ticket')
    )
    with op.batch_alter_table('ea_trade', schema=None) as batch_op:
        batch_op.create_index('idx_trade_challenge_close', ['challenge_purchase_id', 'close_time'], unique=False)
        batch_op.create_index('idx_trade_challenge_status', ['challenge_purchase_id', 'status'], unique=False)
        batch_op.create_index('idx_trade_magic', ['magic', 'challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_close_time'), ['close_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_magic'), ['magic'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_open_time'), ['open_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_ea_trade_ticket'), ['ticket'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gateway_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_payment_id'), ['payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)

    op.create_table('payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('profit_share_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('bank_account_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_payout_date'), ['payout_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_user_id'), ['user_id'], unique=False)

    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_close_time'), ['close_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_open_time'), ['open_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_trade_id'), ['trade_id'], unique=True)

    op.create_table('rule_violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_purchase_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_value_limit', sa.Float(), nullable=True),
    sa.Column('rule_value_actual', sa.Float(), nullable=True),
    sa.Column('violation_message', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_hard_fail', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('violated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_purchase_id'], ['challenge_purchase.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['account_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_violation', schema=None) as batch_op:
        batch_op.create_index('idx_violation_challenge_rule', ['challenge_purchase_id', 'rule_name'], unique=False)
        batch_op.create_index('idx_violation_severity_date', ['severity', 'violated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_violation_challenge_purchase_id'), ['challenge_purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_violation_is_hard_fail'), ['is_hard_fail'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_violation_rule_name'), ['rule_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_violation_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_violation_violated_at'), ['violated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_violation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_violation_violated_at'))
        batch_op.drop_index(batch_op.f('ix_rule_violation_severity'))
        batch_op.drop_index(batch_op.f('ix_rule_violation_rule_name'))
        batch_op.drop_index(batch_op.f('ix_rule_violation_is_hard_fail'))
        batch_op.drop_index(batch_op.f('ix_rule_violation_challenge_purchase_id'))
        batch_op.drop_index('idx_violation_severity_date')
        batch_op.drop_index('idx_violation_challenge_rule')

    op.drop_table('rule_violation')
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_trade_id'))
        batch_op.drop_index(batch_op.f('ix_trade_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_status'))
        batch_op.drop_index(batch_op.f('ix_trade_open_time'))
        batch_op.drop_index(batch_op.f('ix_trade_created_at'))
        batch_op.drop_index(batch_op.f('ix_trade_close_time'))
        batch_op.drop_index(batch_op.f('ix_trade_challenge_purchase_id'))

    op.drop_table('trade')
    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_user_id'))
        batch_op.drop_index(batch_op.f('ix_payout_status'))
        batch_op.drop_index(batch_op.f('ix_payout_payout_date'))
        batch_op.drop_index(batch_op.f('ix_payout_due_date'))
        batch_op.drop_index(batch_op.f('ix_payout_created_at'))
        batch_op.drop_index(batch_op.f('ix_payout_challenge_purchase_id'))

    op.drop_table('payout')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_challenge_purchase_id'))

    op.drop_table('payment')
    with op.batch_alter_table('ea_trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ea_trade_ticket'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_symbol'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_status'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_open_time'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_magic'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_is_archived'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_created_at'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_close_time'))
        batch_op.drop_index(batch_op.f('ix_ea_trade_challenge_purchase_id'))
        batch_op.drop_index('idx_trade_magic')
        batch_op.drop_index('idx_trade_challenge_status')
        batch_op.drop_index('idx_trade_challenge_close')

    op.drop_table('ea_trade')
    with op.batch_alter_table('daily_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_snapshot_violated_daily_dd'))
        batch_op.drop_index(batch_op.f('ix_daily_snapshot_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_daily_snapshot_is_trading_day'))
        batch_op.drop_index(batch_op.f('ix_daily_snapshot_had_manual_trades'))
        batch_op.drop_index(batch_op.f('ix_daily_snapshot_challenge_purchase_id'))
        batch_op.drop_index('idx_daily_trading_status')
        batch_op.drop_index('idx_daily_challenge_date')

    op.drop_table('daily_snapshot')
    with op.batch_alter_table('account_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_snapshot_timestamp'))
        batch_op.drop_index(batch_op.f('ix_account_snapshot_profit_from_start'))
        batch_op.drop_index(batch_op.f('ix_account_snapshot_mt5_login'))
        batch_op.drop_index(batch_op.f('ix_account_snapshot_is_archived'))
        batch_op.drop_index(batch_op.f('ix_account_snapshot_drawdown_from_peak'))
        batch_op.drop_index(batch_op.f('ix_account_snapshot_challenge_purchase_id'))
        batch_op.drop_index('idx_snapshot_challenge_timestamp')
        batch_op.drop_index('idx_snapshot_challenge_archived')

    op.drop_table('account_snapshot')
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_ticket_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_priority'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_created_at'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_assigned_to'))

    op.drop_table('support_ticket')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_violation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_trading_days_completed'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_status'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_start_date'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_serial_no'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_mt5_login'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_last_updated'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_last_heartbeat'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_end_date'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_ea_connected'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_daily_start_date'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_completed_at'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_challenge_token'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_challenge_template_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_challenge_code'))

    op.drop_table('challenge_purchase')
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_admin_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_admin_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_log_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_log_action'))

    op.drop_table('admin_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_verified'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_kyc_status'))
        batch_op.drop_index(batch_op.f('ix_user_is_banned'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email_verified'))
        batch_op.drop_index(batch_op.f('ix_user_email_verification_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_country'))

    op.drop_table('user')
    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_template_name'))
        batch_op.drop_index(batch_op.f('ix_challenge_template_is_active'))
        batch_op.drop_index(batch_op.f('ix_challenge_template_created_at'))

    op.drop_table('challenge_template')
    # ### end Alembic commands ###
