"""add safety rules

Revision ID: 071deb0d1bab
Revises: 93fcb124ff91
Create Date: 2026-06-22 21:29:53.576789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071deb0d1bab'
down_revision = '93fcb124ff91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sl_violation_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_violation_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sl_mandatory_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sl_grace_period_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_risk_per_trade_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('activity_rule_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_inactive_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.drop_column('max_inactive_days')
        batch_op.drop_column('activity_rule_enabled')
        batch_op.drop_column('max_risk_per_trade_percent')
        batch_op.drop_column('sl_grace_period_minutes')
        batch_op.drop_column('sl_mandatory_enabled')

    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_column('activity_violation_count')
        batch_op.drop_column('sl_violation_count')

    # ### end Alembic commands ###
