"""Add rule engine fields and tables

Revision ID: 12cc72999b9c
Revises: 9c89eef04452
Create Date: 2026-05-19 20:01:06.745866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cc72999b9c'
down_revision = '9c89eef04452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_equity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('daily_drawdown', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_drawdown', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trading_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lowest_equity_today', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('highest_equity_today', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('day_start_equity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monitoring_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('review_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phase1_completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('phase2_started_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_column('funded_at')
        batch_op.drop_column('phase2_started_at')
        batch_op.drop_column('phase1_completed_at')
        batch_op.drop_column('review_required')
        batch_op.drop_column('monitoring_status')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('day_start_equity')
        batch_op.drop_column('highest_equity_today')
        batch_op.drop_column('lowest_equity_today')
        batch_op.drop_column('trading_days')
        batch_op.drop_column('profit_percent')
        batch_op.drop_column('overall_drawdown')
        batch_op.drop_column('daily_drawdown')
        batch_op.drop_column('highest_equity')

    # ### end Alembic commands ###
