"""add violation tracking fields

Revision ID: 21b66b95dba7
Revises: e3a9b7c2d4f1
Create Date: 2026-06-10 23:24:30.613436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b66b95dba7'
down_revision = 'e3a9b7c2d4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lowest_equity_lifetime', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lowest_equity_phase', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('violation_reviewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_violation_evidence_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_column('last_violation_evidence_id')
        batch_op.drop_column('violation_reviewed')
        batch_op.drop_column('lowest_equity_phase')
        batch_op.drop_column('lowest_equity_lifetime')

    # ### end Alembic commands ###
