"""add faq and support ticket fields

Revision ID: 414c54b6f37a
Revises: 9caac6dba091
Create Date: 2026-05-17 11:59:57.149453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414c54b6f37a'
down_revision = '9caac6dba091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('helpful_yes', sa.Integer(), nullable=True),
    sa.Column('helpful_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_is_pinned'), ['is_pinned'], unique=False)

    op.create_table('webhook_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_log_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_log_status'), ['status'], unique=False)

    op.create_table('ticket_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_admin_reply', sa.Boolean(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_message_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_user_read_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_admin_read_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_support_ticket_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_unique_constraint('uq_support_ticket_ticket_number', ['ticket_number'])
        batch_op.drop_column('message')
        batch_op.drop_column('resolution')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_compact_view',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_compact_view',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('uq_support_ticket_ticket_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_support_ticket_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_category'))
        batch_op.drop_column('last_admin_read_at')
        batch_op.drop_column('last_user_read_at')
        batch_op.drop_column('last_reply_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('admin_note')
        batch_op.drop_column('category')
        batch_op.drop_column('ticket_number')

    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_message_ticket_id'))

    op.drop_table('ticket_message')
    with op.batch_alter_table('webhook_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_log_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_log_order_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_webhook_log_created_at'))

    op.drop_table('webhook_log')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_faq_category'))

    op.drop_table('faq')
    # ### end Alembic commands ###
