"""Add phase tracking and distance metrics

Revision ID: 7098207a5b02
Revises: 12cc72999b9c
Create Date: 2026-05-19 20:28:13.514953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7098207a5b02'
down_revision = '12cc72999b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase_start_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase_start_equity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase_start_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('phase_trading_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase_profit_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase_daily_drawdown', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase_day_start_equity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase_lowest_equity_today', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase_daily_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('distance_to_payout', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_to_breach', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_trade_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_column('last_trade_date')
        batch_op.drop_column('distance_to_breach')
        batch_op.drop_column('distance_to_payout')
        batch_op.drop_column('phase_daily_start_date')
        batch_op.drop_column('phase_lowest_equity_today')
        batch_op.drop_column('phase_day_start_equity')
        batch_op.drop_column('phase_daily_drawdown')
        batch_op.drop_column('phase_profit_percent')
        batch_op.drop_column('phase_trading_days')
        batch_op.drop_column('phase_start_date')
        batch_op.drop_column('phase_start_equity')
        batch_op.drop_column('phase_start_balance')

    # ### end Alembic commands ###
