"""add created_at to challenge_purchase

Revision ID: 72af0b6d448b
Revises: 85a6f3058489
Create Date: 2026-05-31 12:22:37.969650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72af0b6d448b'
down_revision = '85a6f3058489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_challenge_purchase_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_created_at'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
