"""add phase columns to challenge_template

Revision ID: 7c88fbce1548
Revises: 86a97bc0ab32
Create Date: 2026-05-17 09:19:17.240153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c88fbce1548'
down_revision = '86a97bc0ab32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.alter_column('challenge_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'one_phase'::character varying"))
        batch_op.alter_column('current_phase',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_terminated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_challenge_purchase_challenge_type'), ['challenge_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_is_terminated'), ['is_terminated'], unique=False)

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase1_target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase1_daily_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase1_overall_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase1_min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase1_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase1_leverage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phase1_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phase2_target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase2_daily_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase2_overall_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase2_min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase2_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase2_leverage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phase2_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instant_daily_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('instant_overall_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('instant_min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instant_leverage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instant_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('challenge_type', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_challenge_template_challenge_type'), ['challenge_type'], unique=False)
        batch_op.drop_column('max_overall_loss')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('min_trading_days')
        batch_op.drop_column('profit_target')
        batch_op.drop_column('leverage')
        batch_op.drop_column('max_daily_loss')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cf_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cf_payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_session_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gateway_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gateway_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refund_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refund_eligible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('refund_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refund_requested_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('refund_processed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('expected_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_payment_cf_order_id'), ['cf_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_challenge_template_id'), ['challenge_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_refund_status'), ['refund_status'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['refund_verified_by'], ['id'])

    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.alter_column('ticket_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'General'::character varying"))
        batch_op.alter_column('last_reply_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_user_read_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_admin_read_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_support_ticket_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_ticket_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_unique_constraint(None, ['ticket_number'])
        batch_op.drop_column('resolution')
        batch_op.drop_column('closed_by')
        batch_op.drop_column('message')
        batch_op.drop_column('attachment')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('trading_alias',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('trading_alias',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('closed_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_support_ticket_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_support_ticket_category'))
        batch_op.alter_column('last_admin_read_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_user_read_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_reply_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'General'::character varying"))
        batch_op.alter_column('ticket_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_refund_status'))
        batch_op.drop_index(batch_op.f('ix_payment_challenge_template_id'))
        batch_op.drop_index(batch_op.f('ix_payment_cf_order_id'))
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('expected_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.drop_column('refund_processed_at')
        batch_op.drop_column('refund_requested_at')
        batch_op.drop_column('refund_verified_by')
        batch_op.drop_column('refund_eligible')
        batch_op.drop_column('refund_status')
        batch_op.drop_column('gateway_message')
        batch_op.drop_column('gateway_status')
        batch_op.drop_column('payment_session_id')
        batch_op.drop_column('cf_payment_id')
        batch_op.drop_column('cf_order_id')
        batch_op.drop_column('paid_amount')

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_daily_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('leverage', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profit_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('min_trading_days', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_overall_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_challenge_template_challenge_type'))
        batch_op.drop_column('challenge_type')
        batch_op.drop_column('instant_rules')
        batch_op.drop_column('instant_leverage')
        batch_op.drop_column('instant_min_days')
        batch_op.drop_column('instant_overall_loss')
        batch_op.drop_column('instant_daily_loss')
        batch_op.drop_column('phase2_rules')
        batch_op.drop_column('phase2_leverage')
        batch_op.drop_column('phase2_duration')
        batch_op.drop_column('phase2_min_days')
        batch_op.drop_column('phase2_overall_loss')
        batch_op.drop_column('phase2_daily_loss')
        batch_op.drop_column('phase2_target')
        batch_op.drop_column('phase1_rules')
        batch_op.drop_column('phase1_leverage')
        batch_op.drop_column('phase1_duration')
        batch_op.drop_column('phase1_min_days')
        batch_op.drop_column('phase1_overall_loss')
        batch_op.drop_column('phase1_daily_loss')
        batch_op.drop_column('phase1_target')

    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_is_terminated'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_challenge_type'))
        batch_op.alter_column('is_terminated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('current_phase',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('challenge_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'one_phase'::character varying"))

    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_payment_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_action'))

    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
