"""Add Coupon tables

Revision ID: 85a6f3058489
Revises: 86f8480a5d9e
Create Date: 2026-05-26 15:58:53.451799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a6f3058489'
down_revision = '86f8480a5d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payment_coupon_id', 'coupon', ['coupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_coupon_id', type_='foreignkey')
        batch_op.drop_column('coupon_id')

    # ### end Alembic commands ###
