"""add phase rules columns

Revision ID: 86a97bc0ab32
Revises: 414c54b6f37a
Create Date: 2026-05-17 13:05:23.453808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a97bc0ab32'
down_revision = '414c54b6f37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase1_target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase1_daily_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase1_overall_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase1_min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase1_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase1_leverage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phase2_target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase2_daily_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase2_overall_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phase2_min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase2_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase2_leverage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instant_daily_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('instant_overall_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('instant_min_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instant_leverage', sa.String(length=20), nullable=True))
        batch_op.drop_column('min_trading_days')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('max_overall_loss')
        batch_op.drop_column('leverage')
        batch_op.drop_column('profit_target')
        batch_op.drop_column('max_daily_loss')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_daily_loss', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('profit_target', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('leverage', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_overall_loss', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('min_trading_days', sa.INTEGER(), nullable=False))
        batch_op.drop_column('instant_leverage')
        batch_op.drop_column('instant_min_days')
        batch_op.drop_column('instant_overall_loss')
        batch_op.drop_column('instant_daily_loss')
        batch_op.drop_column('phase2_leverage')
        batch_op.drop_column('phase2_duration')
        batch_op.drop_column('phase2_min_days')
        batch_op.drop_column('phase2_overall_loss')
        batch_op.drop_column('phase2_daily_loss')
        batch_op.drop_column('phase2_target')
        batch_op.drop_column('phase1_leverage')
        batch_op.drop_column('phase1_duration')
        batch_op.drop_column('phase1_min_days')
        batch_op.drop_column('phase1_overall_loss')
        batch_op.drop_column('phase1_daily_loss')
        batch_op.drop_column('phase1_target')

    # ### end Alembic commands ###
