"""update notifications schema and add user notifications

Revision ID: 86f8480a5d9e
Revises: 9e6acc10156b
Create Date: 2026-05-26 14:02:04.981095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f8480a5d9e'
down_revision = '9e6acc10156b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.create_index(batch_op.f('ix_notification_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_global'), ['is_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_foreign_key('fk_notification_created_by_admin_id_user', 'user', ['created_by_admin_id'], ['id'])
        batch_op.create_foreign_key('fk_notification_target_user_id_user', 'user', ['target_user_id'], ['id'])
        batch_op.drop_column('is_read')
        batch_op.drop_column('read_at')
        batch_op.drop_column('action_url')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('user_id')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('notification_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('action_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_notification_created_by_admin_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_notification_target_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_notification_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_notification_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_global'))
        batch_op.drop_index(batch_op.f('ix_notification_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_notification_expires_at'))
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('target_user_id')
        batch_op.drop_column('is_global')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
