"""add sl and tp to TradeHistory

Revision ID: 8e2ee6d17010
Revises: 7098207a5b02
Create Date: 2026-05-21 12:43:13.510166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2ee6d17010'
down_revision = '7098207a5b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_column('tp')
        batch_op.drop_column('sl')

    # ### end Alembic commands ###
