"""add created_at to challenge_purchase

Revision ID: 93fcb124ff91
Revises: 05c27b83f109
Create Date: 2026-06-20 14:00:06.693859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fcb124ff91'
down_revision = '05c27b83f109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_column('flagged_reason')
        batch_op.drop_column('risk_level')

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.alter_column('phase1_daily_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase1_overall_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase2_daily_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase2_overall_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('instant_daily_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('instant_overall_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'equity'"))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('dedupe_key',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_notification_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_notification_type'), ['notification_type'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliate_code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('affiliate_discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('visible_to_partner', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.create_index(batch_op.f('ix_payment_affiliate_code'), ['affiliate_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_visible_to_partner'), ['visible_to_partner'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfie_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('affiliate_code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('affiliate_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('affiliate_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('affiliate_disabled_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('affiliate_code_reset_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_affiliate_banned'), ['affiliate_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affiliate_code'), ['affiliate_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_affiliate_enabled'), ['affiliate_enabled'], unique=False)
        batch_op.create_foreign_key('fk_user_lead_status_id', 'lead_statuses', ['lead_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_affiliate_enabled'))
        batch_op.drop_index(batch_op.f('ix_user_affiliate_code'))
        batch_op.drop_index(batch_op.f('ix_user_affiliate_banned'))
        batch_op.drop_column('affiliate_code_reset_at')
        batch_op.drop_column('affiliate_disabled_reason')
        batch_op.drop_column('affiliate_banned')
        batch_op.drop_column('affiliate_enabled')
        batch_op.drop_column('affiliate_code')
        batch_op.drop_column('selfie_url')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_visible_to_partner'))
        batch_op.drop_index(batch_op.f('ix_payment_affiliate_code'))
        batch_op.drop_column('visible_to_partner')
        batch_op.drop_column('affiliate_discount_amount')
        batch_op.drop_column('affiliate_code')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_dedupe_key'))
        batch_op.alter_column('dedupe_key',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.alter_column('instant_overall_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('instant_daily_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase2_overall_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase2_daily_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase1_overall_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equity'"))
        batch_op.alter_column('phase1_daily_dd_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'equity'"))

    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('flagged_reason', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
