"""add challenge type and rules columns

Revision ID: 9caac6dba091
Revises: da9af13a874f
Create Date: 2026-05-17 11:06:51.652586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caac6dba091'
down_revision = 'da9af13a874f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_type', sa.String(length=20), nullable=False, server_default='one_phase'))
        batch_op.add_column(sa.Column('current_phase', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('is_terminated', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_challenge_purchase_challenge_type'), ['challenge_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_purchase_is_terminated'), ['is_terminated'], unique=False)

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_type', sa.String(length=20), nullable=False, server_default='one_phase'))
        batch_op.add_column(sa.Column('phase1_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phase2_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instant_rules', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_challenge_template_challenge_type'), ['challenge_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_is_terminated'))
        batch_op.drop_index(batch_op.f('ix_challenge_purchase_challenge_type'))
        batch_op.drop_column('is_terminated')
        batch_op.drop_column('current_phase')
        batch_op.drop_column('challenge_type')

    with op.batch_alter_table('challenge_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_template_challenge_type'))
        batch_op.drop_column('instant_rules')
        batch_op.drop_column('phase2_rules')
        batch_op.drop_column('phase1_rules')
        batch_op.drop_column('challenge_type')
    # ### end Alembic commands ###
