"""add created_at to challenge_purchase

Revision ID: be633688cce9
Revises: 9cadde2b9793
Create Date: 2026-06-08 13:19:14.312701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be633688cce9'
down_revision = '9cadde2b9793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_history', schema=None) as batch_op:
        batch_op.drop_column('commission')
        batch_op.drop_column('swap')

    # ### end Alembic commands ###
