"""Final Cashfree migration with WebhookLog

Revision ID: cfb59ab46efa
Revises: 40f5c265cd8e
Create Date: 2026-05-14 23:57:52.364101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb59ab46efa'
down_revision = '40f5c265cd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_amount', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('challenge_template_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_challenge_template_id'), ['challenge_template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_challenge_template_id'))
        batch_op.drop_column('challenge_template_id')
        batch_op.drop_column('expected_amount')

    # ### end Alembic commands ###
