"""Update payment model

Revision ID: da9af13a874f
Revises: cfb59ab46efa
Create Date: 2026-05-16 10:35:57.419089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9af13a874f'
down_revision = 'cfb59ab46efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cf_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cf_payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_session_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gateway_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gateway_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refund_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refund_eligible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('refund_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refund_requested_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('refund_processed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('expected_amount',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_payment_cf_order_id'), ['cf_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_refund_status'), ['refund_status'], unique=False)
        batch_op.create_foreign_key('fk_payment_refund_verified_by_user', 'user', ['refund_verified_by'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_alias', sa.String(length=50), nullable=True, server_default=''))
        batch_op.add_column(sa.Column('trader_level', sa.String(length=50), nullable=True, server_default='Starter'))
        batch_op.add_column(sa.Column('is_compact_view', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_compact_view')
        batch_op.drop_column('trader_level')
        batch_op.drop_column('trading_alias')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_refund_verified_by_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_refund_status'))
        batch_op.drop_index(batch_op.f('ix_payment_cf_order_id'))
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('expected_amount',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_column('refund_processed_at')
        batch_op.drop_column('refund_requested_at')
        batch_op.drop_column('refund_verified_by')
        batch_op.drop_column('refund_eligible')
        batch_op.drop_column('refund_status')
        batch_op.drop_column('gateway_message')
        batch_op.drop_column('gateway_status')
        batch_op.drop_column('payment_session_id')
        batch_op.drop_column('cf_payment_id')
        batch_op.drop_column('cf_order_id')
        batch_op.drop_column('paid_amount')

    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_payment_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_action'))

    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
