"""initial migration with moderator system

Revision ID: f7849b5890fc
Revises: 
Create Date: 2026-07-15 23:34:56.875823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7849b5890fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('kyc_rejection_reason')
        batch_op.drop_column('kyc_rejected_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_rejected_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejection_reason', sa.TEXT(), server_default=sa.text("('')"), nullable=True))

    # ### end Alembic commands ###
